(ns examples.map_usa
  (:require [logic.util :refer (oneof combine-syms_)]))

(def colors '[red green blue yellow])

(def countries '[c al ak az ar ca co ct de fl ga id il in ia ks ky la 
                 me md ma mi mn ms mo mt ne nv nh nj nm ny nc nd oh ok 
                 or pa ri sc tn tx ut vt va wa wv wi wy])

(defn one-color [country colors]
  (oneof (map #(combine-syms_ country %) colors)))

(defn countries-one-color [countries colors]
  (apply list 'and (map #(one-color % colors) countries)))

(defn adjacent [c1 c2]
  (apply list 'and (map #(list 'or (list 'not %1) (list 'not %2))
                     (map #(combine-syms_ c1 %) colors)
                     (map #(combine-syms_ c2 %) colors))))

(def fml 
  (list 'and
    (countries-one-color countries colors)
    (adjacent 'wa 'or)
    (adjacent 'wa 'id)
		(adjacent 'or 'id)
		(adjacent 'or 'nv)
		(adjacent 'or 'ca)
		(adjacent 'ca 'nv)
		(adjacent 'ca 'az)
		(adjacent 'az 'nm)
		(adjacent 'az 'nv)
		(adjacent 'az 'ut)
		(adjacent 'nv 'ut)
		(adjacent 'nv 'id)
		(adjacent 'id 'mt)
		(adjacent 'id 'ut)
		(adjacent 'id 'wy)
		(adjacent 'ut 'wy)
		(adjacent 'ut 'co)
		(adjacent 'nm 'tx)
		(adjacent 'nm 'ok)
		(adjacent 'nm 'co)
		(adjacent 'co 'ok)
		(adjacent 'co 'ks)
		(adjacent 'co 'ne)
		(adjacent 'co 'wy)
		(adjacent 'wy 'ne)
		(adjacent 'wy 'sd)
		(adjacent 'wy 'mt)
		(adjacent 'mt 'sd)
		(adjacent 'mt 'nd)
		(adjacent 'nd 'sd)
		(adjacent 'nd 'mn)
		(adjacent 'sd 'ne)
		(adjacent 'sd 'ia)
		(adjacent 'sd 'mn)
		(adjacent 'ne 'ks)
		(adjacent 'ne 'mo)
		(adjacent 'ne 'ia)
		(adjacent 'ks 'ok)
		(adjacent 'ks 'mo)
		(adjacent 'ok 'tx)
		(adjacent 'ok 'ar)
		(adjacent 'ok 'mo)
		(adjacent 'tx 'la)
		(adjacent 'la 'ms)
		(adjacent 'la 'ar)
		(adjacent 'ar 'ms)
		(adjacent 'ar 'tn)
		(adjacent 'ar 'mo)
		(adjacent 'mo 'tn)
		(adjacent 'mo 'ky)
		(adjacent 'mo 'il)
		(adjacent 'mo 'ia)
		(adjacent 'ia 'il)
		(adjacent 'ia 'wi)
		(adjacent 'ia 'mn)
		(adjacent 'mn 'wi)
		(adjacent 'wi 'il)
		(adjacent 'wi 'mi)
		(adjacent 'il 'ky)
		(adjacent 'il 'in)
		(adjacent 'ms 'al)
		(adjacent 'ms 'tn)
		(adjacent 'al 'fl)
		(adjacent 'al 'ga)
		(adjacent 'tn 'ga)
		(adjacent 'tn 'nc)
		(adjacent 'tn 'va)
		(adjacent 'tn 'ky)
		(adjacent 'ky 'va)
		(adjacent 'ky 'wv)
		(adjacent 'ky 'oh)
		(adjacent 'ky 'in)
		(adjacent 'in 'oh)
		(adjacent 'in 'mi)
		(adjacent 'oh 'pa)
		(adjacent 'oh 'wv)
		(adjacent 'wv 'pa)
		(adjacent 'wv 'md)
		(adjacent 'wv 'va)
		(adjacent 'va 'md)
		(adjacent 'va 'dc)
		(adjacent 'vc 'nc)
		(adjacent 'nc 'sc)
		(adjacent 'sc 'ga)
		(adjacent 'ga 'fl)
		(adjacent 'dc 'md)
		(adjacent 'md 'de)
		(adjacent 'md 'pa)
		(adjacent 'de 'pa)
		(adjacent 'de 'nj)
		(adjacent 'nj 'pa)
		(adjacent 'nj 'ny)
		(adjacent 'pa 'ny)
		(adjacent 'ny 'ct)
		(adjacent 'ny 'ma)
		(adjacent 'ny 'vt)
		(adjacent 'ct 'ma)
		(adjacent 'ct 'ri)
		(adjacent 'ma 'ri)
		(adjacent 'ma 'vt)
		(adjacent 'ma 'nh)
		(adjacent 'vt 'nh)
		(adjacent 'nh 'me)))
		
